config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :tickets
  end

  root 'static_pages#home'
  resources :organizations
  resources :tickets
  resources :products

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :users
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :tickets
  default_scope -> { order(name: :asc, version: :desc) }

  def name_and_version
    "#{self.name} v#{self.version}"
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :organization
  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  def index
    @tickets = Ticket.all
  end

  def show
    @ticket = Ticket.find(params[:id])
  end

  def new
    @ticket = current_user.tickets.build
  end

  def create
    @ticket = current_user.tickets.build(ticket_params)

    if @ticket.save
      flash[:success] = "Ticket created"

      redirect_to @ticket
    else
      render 'ticket/new'
    end
  end

  private

    def ticket_params
      params.require(:ticket).permit(:title, :text, :user_id, :product_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @ticket = current_user.tickets.build
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def ticket_status(ticket)
    if ticket.is_open
      "Open"
    else
      "Closed"
    end
  end

  def ticket_status_class(ticket)
    if ticket.is_open
      "success"
    else
      "danger"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    TeoTracker by Pixel Cartel
  </small>
  <nav>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "teotracker", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
            <li class="nonlink"><%= current_user.email %></li>
            <li><%= link_to 'Users', users_path %></li>
            <li><%= link_to 'Tickets', tickets_path %></li>
            <li><%= link_to 'Products', products_path %></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teotracker</title>
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <!--<% if notice %>-->
      <!--<p class="alert alert-success"><%= notice %></p>-->
  <!--<% end %>-->
  <!--<% if alert %>-->
      <!--<p class="alert alert-danger"><%= alert %></p>-->
  <!--<% end %>-->
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/products/_product.html.erb
<tr>
  <td><h4>
    <%= product.name %> <small>v<%= product.version %></small>
  </h4></td>
</tr>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <h3>Products</h3>
    <div class="column">
      <table class="table table-striped">
        <tbody>
        <% @products.each do |product| %>
            <tr>
              <%= render product %>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>TeoTracker is the simple, effective issue tracker.</h1>

  <h2>
    From planning, to coding, to testing, to customer support,
    DoneDone is the refreshingly simple issue tracker.
    No more spreadsheets, sticky notes, and emails
    about web and software projects. Just one
    uncomplicated, central hub.
  </h2>

  <% if user_signed_in? %>
      <%= link_to "View your tickets", user_path(current_user), class: "btn btn-lg btn-primary" %>
  <% else %>
      <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>

<%= link_to image_tag("http://rubyonrails.org/images/rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/tickets/_ticket.html.erb
<tr>
  <td><h4>
  <span class="btn btn-<%= ticket_status_class ticket %>"><%= ticket_status ticket %></span>
  <%= ticket.title %> <small><%= "#{ticket.product.name} v#{ticket.product.version}" %></small>
  </h4></td>
</tr>
<tr>
  <td>
<p><%= ticket.text %></p>
<h4><small>Product Serial # <%= ticket.serial %></small></h4>
<h5><small>opened <%= time_ago_in_words ticket.created_at %> ago by <%= link_to "#{ticket.user.first_name} #{ticket.user.last_name}", user_path(ticket.user) %></small></h5>
  </td>
</tr>

app/views/tickets/_ticket_form.html.erb
<%= form_for [@user, @ticket] do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.label :product %>
      <%= f.collection_select :product_id, Product.all, :id, :name_and_version %>
    </div>
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title, placeholder: 'Issue title, e.g. Strange readings on FME scale' %>
    </div>
    <div>
      <%= f.label :text %>
      <%= f.text_area :text, placeholder: 'Issue text, e.g. Bias voltage low when C2 diode enters avalanche mode' %>
    </div>
    <%= f.submit 'Submit issue', class: 'btn btn-primary' %>
<% end %>

app/views/tickets/index.html.erb
<div class="container">
  <div class="row">
    <h3>Tickets</h3>
    <div class="column">
      <table class="table table-striped">
        <tbody>
        <% @tickets.each do |ticket| %>
            <tr>
              <%= render ticket %>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/tickets/show.html.erb
<h3>Ticket for <%= @ticket.product.name %> <%= @ticket.product.version %></h3>
<h5>Submitted by <%= @ticket.user.first_name %> <%= @ticket.user.last_name %> (<%= @ticket.user.organization.name %>)</h5>
<dl>
    <dt><%= @ticket.title %></dt>
    <dd><%= @ticket.text %></dd>
</dl>

app/views/users/_user.html.erb
<td><%= link_to "#{user.first_name} #{user.last_name}", user_path(user) %></td>
<td><%= user.email %></td>
<td><%= user.phone %></td>
<td><%= user.department %></td>
<td><%= user.organization.name %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table table-striped">
        <tbody>
        <thead>
        <td>Name</td>
        <td>Email</td>
        <td>Phone</td>
        <td>Department</td>
        <td>Organization</td>
        </thead>
        <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.first_name %> <%= @user.last_name %></p>
<p>Email: <%= @user.email %></p>
<p>Last sign in: <%= @user.last_sign_in_at.in_time_zone('EST') %></p>
<p>Organization: <%= @user.organization.name %></p>
<p>Department: <%= @user.department %></p>

<h3>Tickets</h3>
<% if @user.tickets.any? %>
    <table class="table table-bordered">
        <%= render @user.tickets %>
    </table>
<% else %>
    No tickets; you're problem-free!
<% end %>

<div>
  <% if @user == current_user %>
    <%= render 'tickets/ticket_form' %>
  <% end %>
</div>